services:
  payment-module:
    container_name: payment-module
    image: openjdk:17-oracle
    ports:
      - 17004:17004
    volumes:
      - ./payment-module/build/payment-module-0.0.1-SNAPSHOT.jar:/payment-module.jar
    command: [ 'java', '-jar', '/payment-module.jar' ]
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_PASSWORD=${DB_PASSWORD}
      - BANK_ACCOUNT_ID=${BANK_ACCOUNT_ID}
    networks:
      - gadget

  payment-mock:
    container_name: payment-mock
    image: openjdk:17-oracle
    ports:
      - 17006:17006
    volumes:
      - ./payment-mock/target/payment-mock-0.0.1-SNAPSHOT.jar:/payment-mock.jar
    command: [ 'java', '-jar', '/payment-mock.jar' ]
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - gadget

networks:
  gadget:
